/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,jsx,ts,tsx}',
    './src/components/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {},
    // colors: {
    //   'pc-darker': '#191a21',
    //   'pc-dark': '#1F2028',
    //   'pc-light': '#F9EBD7',
    //   'pc-yellow': '#EFBB35',
    //   'pc-pink': '#FFA7C4',
    // },
    colors: ({ colors }) => ({
      // 'pc-darker': '#191a21',
      'pc-darker': '#16171c',
      'pc-dark': '#1F2028',
      'pc-light': '#F9EBD7',
      'cc-yellow': '#CAF17C',
      'pc-yellow': '#EFBB35',
      'pc-pink': '#FFA7C4',
      inherit: colors.inherit,
      current: colors.current,
      transparent: colors.transparent,
      black: colors.black,
      white: colors.white,
      slate: colors.slate,
      gray: colors.gray,
      zinc: colors.zinc,
      neutral: colors.neutral,
      stone: colors.stone,
      red: colors.red,
      orange: colors.orange,
      amber: colors.amber,
      yellow: colors.yellow,
      lime: colors.lime,
      green: colors.green,
      emerald: colors.emerald,
      teal: colors.teal,
      cyan: colors.cyan,
      sky: colors.sky,
      blue: colors.blue,
      indigo: colors.indigo,
      violet: colors.violet,
      purple: colors.purple,
      fuchsia: colors.fuchsia,
      pink: colors.pink,
      rose: colors.rose,
    }),
    fontFamily: {
      sans: ['Graphik', 'sans-serif'],
      serif: ['Merriweather', 'serif'],
      mont: ['Montserrat', 'sans-serif'],
      nunito: ['Nunito', 'sans-serif'],
    },
  },
  plugins: [],
}
